using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Draggable : MonoBehaviour
{
    private bool isDragging = false;
    private Vector3 offset;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (isDragging)
        {
            transform.position = Camera.main.ScreenToWorldPoint(Input.mousePosition) + offset;
        }
    }
    private void OnMouseDown()
    {
        //Debug.Log("Mouse Down");
        offset = transform.position - Camera.main.ScreenToWorldPoint(Input.mousePosition);
        isDragging = true;
       // Debug.Log("isDragging = "+ isDragging);
    }
    private void OnMouseUp()
    {
        //Debug.Log("Mouse Up");
        isDragging = false;
        //Debug.Log("isDragging = " + isDragging);
    }
}
